### ISSUE TITLE
Installation issues 

### ISSUE THREAD

**Issue by rdanishb** [AMReX-Microelectronics/FerroX#57]
NA

**Comment by ajnonaka** [comment]
Unless you have an ssh key pair set up you need to clone the https version instead
>> git clone https://github.com/AMReX-Microelectronics/FerroX.git

**Comment by rdanishb** [comment]
while executing make -j 4 for a GPU build and make -j 4 USE_CUDA=FALSE for a CPU build, I'm facing the following error

Loading ../../amrex/Tools/GNUMake/comps/gnu.mak...
/bin/sh: 1: g++: not found
expr: syntax error: unexpected argument ‘8’
../../amrex/Tools/GNUMake/comps/gnu.mak:51: *** GCC < 8 not supported.  Stop.
